services:
  pgdatabase:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8080:80"

networks:
  pg-network:
    driver: bridge

  # taxi_ingest:
  #   build:
  #     context: data_pipeline
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - pgdatabase
  #   env_file:
  #     - .env
  #   environment:
  #     - TABLE_NAME: yellow_taxi_trips
  #     - CSV_URL: "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
  #   volumes:
  #     - ./ny_taxi_postgres_data:/var/lib/postgresql/data